dist: trusty
sudo: required
language: c

git:
  submodules: false

banches:
  only:
  - master
  - coq-master

install:
 - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
 - echo | sudo sh install.sh
 - opam init --disable-sandboxing -j 2 --compiler=4.05.0 -n -y
 - eval $(opam env)
 - opam config var root
 - opam install -j 2 -y elpi
 - opam repo add coq-core-dev http://coq.inria.fr/opam/core-dev
 - opam repo add coq-extra-dev http://coq.inria.fr/opam/extra-dev

matrix:
  include:

  - env: TEST="opam package installation"
    os: linux
    addons:
      apt:
        sources:
        - avsm
    script:
    - opam pin remove coq-elpi -y || true
    - opam pin -y add coq-elpi "https://github.com/${TRAVIS_REPO_SLUG}.git#${TRAVIS_COMMIT}" -v
    - ls `opam config var lib`/coq/user-contrib/elpi/
    - opam remove coq-elpi
    - if [ -d `opam config var lib`/coq/user-contrib/elpi/ ]; then false; else true; fi
