# This is a basic workflow to help you get started with Actions

name: DOC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: './coq-elpi.opam'
        coq_version: '8.13'
        ocaml_version: '4.07-flambda'
        export: 'OPAMWITHDOC'
        after_script: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install alectryon
          sudo chmod -R a+w .
          make doc COQ_ELPI_ALREADY_INSTALLED=1
      env:
        OPAMWITHDOC: 'true'
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: doc
