# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, coq-master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.13'
        ocaml_version:
          - '4.07-flambda'
          - '4.11-flambda'
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: './coq-elpi.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}
        export: 'OPAMWITHTEST OPAMWITHDOC'
        after_install: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install alectryon
      env:
        OPAMWITHTEST: 'true'
        OPAMWITHDOC: ${{ matrix.ocaml_version == '4.07-flambda' }}
