# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, coq-master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.12'
        ocaml_version:
          - 'minimal'
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: './coq-elpi.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}
        custom_script: |
          startGroup Print opam config
            opam config list; opam repo list; opam list
          endGroup
          startGroup Build dependencies
            opam pin add -n -y -k path $PACKAGE $WORKDIR
            opam update -y
            opam install -y -j 4 $PACKAGE --deps-only
          endGroup
          startGroup List installed packages
            opam list
          endGroup
          startGroup Build
            opam install -y -v -j 4 $PACKAGE
            opam list
          endGroup
          startGroup Test Hierarchy Builder
            opam pin add coq-hierarchy-builder 'https://github.com/math-comp/hierarchy-builder.git' --ignore-constraints-on=coq-elpi -y -j 4
            opam remove coq-hierarchy-builder -y
          endGroup
          startGroup Uninstallation test
            opam remove $PACKAGE -y
          endGroup
